
project_id = "warcrow-army-builder"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = 52428800

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "http://warcrow.lovable.ai", "https://warcrow.lovable.ai"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[functions.send-resend-email]
verify_jwt = true

[functions.get-netlify-deployments]
verify_jwt = true

[functions.deepl-translate]
verify_jwt = true
