
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm install --legacy-peer-deps && npm run build"

# Add cache headers for assets - no caching for HTML and API responses
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Add special cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add special cache for images - one year cache
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add cache for fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add CORS headers to ensure API requests work properly
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"

# Ensure Supabase auth paths work properly
[[redirects]]
  from = "/auth/*"
  to = "/auth/:splat"
  status = 200

# Add explicit redirects for login and authentication flows
[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/logout"
  to = "/login"
  status = 302
