[build]
  command = "npm install --legacy-peer-deps && npm run build"

# ✅ Redirect Netlify subdomain to custom domain
[[redirects]]
  from = "/*"
  to = "https://warcrowarmy.com/:splat"
  status = 301
  force = true
  [redirects.conditions]
    Host = "warcrowarmybuilder.netlify.app"

# ✅ Supabase and auth redirects
[[redirects]]
  from = "/auth/*"
  to = "/auth/:splat"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/logout"
  to = "/login"
  status = 302

# ✅ SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ Headers - global no-cache + CORS
[[headers]]
  for = "
