# Redirect Netlify subdomain to main domain
[[redirects]]
  from = "/*"
  to = "https://warcrowarmy.com/:splat"
  status = 301
  force = true
  conditions = { Host = "warcrowarmybuilder.netlify.app" }

# Supabase auth and login routes
[[redirects]]
  from = "/auth/*"
  to = "/auth/:splat"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/logout"
  to = "/login"
  status = 302

# Catch-all for SPA routing - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm install --legacy-peer-deps && npm run build"

# Disable caching for HTML & API
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"

# Long-term cache for JS, CSS, fonts, images
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/art/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/lovable-uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image formats
[[headers]]  for = "/*.jpg"   [headers.values]  Cache-Control = "public, max-age=31536000, immutable"
[[headers]]  for = "/*.jpeg"  [headers.values]  Cache-Control = "public, max-age=31536000, immutable"
[[headers]]  for = "/*.png"   [headers.values]  Cache-Control = "public, max-age=31536000, immutable"
[[headers]]  for = "/*.webp"  [headers.values]  Cache-Control = "public, max-age=31536000, immutable"
[[headers]]  for = "/*.gif"   [headers.values]  Cache-Control = "public, max-age=31536000, immutable"
[[headers]]  for = "/*.svg"   [headers.values]  Cache-Control = "public, max-age=31536000, immutable"
[[headers]]  for = "/*.ico"   [headers.values]  Cache-Control = "public, max-age=31536000, immutable"

# Fonts
[[headers]]  for = "/*.woff"  [headers.values]  Cache-Control = "public, max-age=31536000, immutable"
[[headers]]  for = "/*.woff2" [headers.values]  Cache-Control = "public, max-age=31536000, immutable"
[[headers]]  for = "/*.ttf"   [headers.values]  Cache-Control = "public, max-age=31536000, immutable"
[[headers]]  for = "/*.otf"   [headers.values]  Cache-Control = "public, max-age=31536000, immutable"
