
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables with fallbacks for development
const getSupabaseUrl = () => {
  // Check for environment variables (these would be set in your build environment)
  if (typeof window !== 'undefined') {
    // In browser, these would come from build-time environment variables
    // that are injected into the bundle
    const envUrl = (window as any).__SUPABASE_URL__;
    if (envUrl) return envUrl;
  }
  
  // Fallback to the current hardcoded value
  return "https://odqyoncwqawdzhquxcmh.supabase.co";
};

const getSupabaseAnonKey = () => {
  // Check for environment variables
  if (typeof window !== 'undefined') {
    const envKey = (window as any).__SUPABASE_ANON_KEY__;
    if (envKey) return envKey;
  }
  
  // Fallback to the current hardcoded value
  return "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kcXlvbmN3cWF3ZHpocXV4Y21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1MTQwMzQsImV4cCI6MjA1MTA5MDAzNH0.Yl3Wv21EWxMs6bpCBiHgSNEzNfgh-kLqx_a8dyaKKms";
};

const SUPABASE_URL = getSupabaseUrl();
const SUPABASE_PUBLISHABLE_KEY = getSupabaseAnonKey();

console.log("[Supabase Client] Initializing with URL:", SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
